swagger: "2.0"
info:
  description: "Ini adalah dokumentasi API Specification untuk challenge Get Nearby Places."
  version: "1.0.0"
  title: "Get Nearby Places"
schemes:
- "http"
- "https"
paths:
  /search:
    get:
      tags:
      - Tempat
      summary: Melakukan pencarian tempat/places dengan lokasi terdekat dari sebuah titik koordinat
      parameters:
      - in: query
        name: kategori_id
        schema:
          type: "integer"
        description: "Filter berdasarkan Kategori"
      - in: query
        name: latitude
        schema:
          type: "number"
          format: "float"
        required: true
        description: "Posisi GPS Latitude lokasi user saat ini."
      - in: query
        name: longitude
        schema:
          type: "number"
          format: "float"
        required: true
        description: "Posisi GPS Longitude lokasi user saat ini."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: Daftar tempat/places terdekat dengan lokasi terdekat  
          content:
            application/json:
              schema:
                $ref: '#/definitions/SearchResponse'
definitions:
  SearchResponse:
    type: "object"
    properties:
      data:
        $ref: '#/definitions/ArrayOfPlacess'
      total:
        type: "number"
        example: 2

  ArrayOfPlacess:
    type: "array"
    items:
      $ref: '#/definitions/Place'
    example:
      - id: 1
        name: "Puskesmas Antapani 1"
        kategori_id: 2
        nama_kota: "Kota Bandung"
        nama_kecamatan: "Kecamatan Antapani"
        latitude: -6.9131547622849965
        longitude: 107.66358207489387
      - id: 2
        name: "Puskesmas Antapani 2"
        category_id: 2
        nama_kota: "Kota Bandung"
        nama_kecamatan: "Kecamatan Antapani"
        latitude: -6.916428901401269
        longitude: 107.66058554494842

  Place:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      kategori_id:
        type: "integer"
      nama_kota:
        type: "string"
      nama_kecamatan:
        type: "string"
      latitude:
        type: "number"
        format: "float"
      longitude:
        type: "number"
        format: "float"
    required:
      - latitude
      - longitude
